# Generated by Django 3.0.11 on 2020-12-10 02:20

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.upload_image_path)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
    ]
